from typing import Optional

__version__: str

class Analysis:
    def __init__(self, text: str, options_json: str) -> None: ...
    def report_json(self, pretty: bool) -> str: ...
    def check_access(self, tokens: list[str], path: str) -> str: ...
    def clean_params(self, path: str) -> str: ...
    def markdown(self) -> str: ...
    def html(self) -> str: ...
    def recommended_actions(self) -> list[str]: ...
    def csv_tabs(self) -> list[tuple[str, str]]: ...
    def tab_labels(self) -> list[tuple[str, str]]: ...
    def tagged_csv(self) -> str: ...
    def tsv(self, tab: str) -> Optional[str]: ...
    def filename(self) -> str: ...
    def text(self) -> str: ...
    def crawlers_json(self) -> str: ...

def diff_json(old: Analysis, new: Analysis) -> str: ...
def diff_markdown(old: Analysis, new: Analysis, domain: str) -> str: ...
def default_config() -> str: ...
def validate_config(user_toml: str) -> None: ...
def run_cli(argv: list[str]) -> int: ...
